# Jack's development

development Discord: https://discord.gg/grnbqTMfYC
My FiveM discord: https://discord.gg/P9SjsuhhwP
My discord: JackMF#5286

A simple server chat message script every 5 minutes

## how to config
Go to client.lua and find the Line 1 and change what it says u can DO NOT CHANGE THE ^6 unless u know color codes!!
On line 5 you change change the 300000 to what ever you want (PS: ITS IN MILI SECONDS)

Enjoy!!
